name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all files are checked out

      - name: Debug - List Files
        run: ls -R

      - name: Verify Terraform Configuration Files
        run: |
          if [ -z "$(find . -name '*.tf' 2>/dev/null)" ]; then
            echo "❌ No Terraform files found! Ensure your repository has .tf files."
            exit 1
          fi

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform  # Adjust if needed

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./terraform  # Adjust if needed

      - name: Plan Terraform
        run: terraform plan -out=tfplan
        working-directory: ./terraform  # Adjust if needed
