terraform {
  required_version = ">= 1.3.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }

  backend "azurerm" {
    resource_group_name   = "backupcode"
    storage_account_name  = "backupdatastorage1"
    container_name        = "backup"
    key                   = "infra/terraform.tfstate"
  }
}

provider "azurerm" {
  features {}

  subscription_id = "fb656642-6401-44d5-9de1-14bda10d53e5"
}

# Create Resource Group
resource "azurerm_resource_group" "backupcode" {
  name     = "backupcode"
  location = "East US"
}

# Create Storage Account for Backup
resource "azurerm_storage_account" "backup_storage" {
  name                     = "backupdatastorage1"
  resource_group_name      = azurerm_resource_group.backupcode.name
